### ISSUE TITLE
I can't find a way to message you!  I hope this is ok.

### ISSUE THREAD

**Issue by NextWorldVR** [DanielRBowen/UE4-VR-XPlatform-Menu#1]
This looks amazing!    Free locomotion for UVRF,.  Is it going to be updated for 4.22?  (or,.. might it work?)  The newest UVRF comes built for 4.22 so I am unsure if I can incorporate this but I sure hope so,. AMAZING!  Thank you.

**Comment by NextWorldVR** [comment]
Everything seems to work in 4.22 (converting the Sample Project w/ right click) except turning on the laser with the left Menu button,.  I hope I can find some way to incorporate this into UVRF!

Amazing. thank you!

**Comment by DanielRBowen** [comment]
I am sorry I didn't respond in a timely manner. I had my notification emails from github sent to an email which I do not use and I haven't been checking on this repository. I changed my email which I get notifications for in my settings. I am glad you found out yourself that this still works with 4.22, I am probably should update it and check if it works with newer versions once in a while. I hope your project(s) are going well.
